#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const { DatabaseSync } = require('node:sqlite');

const ROOT = path.resolve(__dirname, '..');
const DEFAULT_SOURCE_DB = path.resolve(ROOT, '..', 'deployable-app', 'file', 'runtime', 'visitor-stats.db');
const DEFAULT_OUTPUT_SQL = path.join(ROOT, 'temp', 'visitor_stats_seed.sql');

function sqlString(value) {
  if (value == null) return 'NULL';
  return `'${String(value).replace(/'/g, "''")}'`;
}

function sqlNumber(value, columnName) {
  const number = Number(value);
  if (!Number.isInteger(number) || number < 0) {
    throw new Error(`${columnName} must be a non-negative integer, got ${value}`);
  }
  return String(number);
}

function ensureParentDir(filePath) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
}

function requireSourceDb(sourcePath) {
  if (!fs.existsSync(sourcePath)) {
    throw new Error(`Missing visitor stats database: ${sourcePath}`);
  }
}

function readRows(database, tableName) {
  return database.prepare(`SELECT * FROM ${tableName}`).all();
}

const sourcePath = path.resolve(process.argv[2] || DEFAULT_SOURCE_DB);
const outputPath = path.resolve(process.argv[3] || DEFAULT_OUTPUT_SQL);
requireSourceDb(sourcePath);

const database = new DatabaseSync(sourcePath, { readOnly: true });
const lines = [
  '-- Generated by scripts/export_visitor_stats_d1.js',
  '-- Import with: wrangler d1 execute <database-name> --file <this-file> --remote',
  'BEGIN TRANSACTION;',
];

for (const row of readRows(database, 'visitor_meta')) {
  lines.push(`INSERT OR REPLACE INTO visitor_meta(key, value) VALUES(${sqlString(row.key)}, ${sqlString(row.value)});`);
}

for (const row of readRows(database, 'visitors')) {
  lines.push(`INSERT OR REPLACE INTO visitors(visitor_id, first_seen_at, last_seen_at, last_visit_counted_at, last_seen_date, ip) VALUES(${sqlString(row.visitor_id)}, ${sqlString(row.first_seen_at)}, ${sqlString(row.last_seen_at)}, ${sqlString(row.last_visit_counted_at)}, ${sqlString(row.last_seen_date)}, ${sqlString(row.ip)});`);
}

for (const row of readRows(database, 'daily_visitors')) {
  lines.push(`INSERT OR IGNORE INTO daily_visitors(date, visitor_id) VALUES(${sqlString(row.date)}, ${sqlString(row.visitor_id)});`);
}

for (const row of readRows(database, 'daily_visitor_totals')) {
  lines.push(`INSERT OR REPLACE INTO daily_visitor_totals(date, visitors) VALUES(${sqlString(row.date)}, ${sqlNumber(row.visitors, 'daily_visitor_totals.visitors')});`);
}

lines.push('COMMIT;', '');
database.close();
ensureParentDir(outputPath);
fs.writeFileSync(outputPath, lines.join('\n'), 'utf8');
console.log(`[visitor-stats-d1] exported ${sourcePath} -> ${outputPath}`);
